# Generated by Django 4.0.1 on 2022-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('technology', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery')),
                ('link', models.URLField(max_length=300, null=True)),
            ],
        ),
    ]
